### ISSUE TITLE
Setting max level option does not have any effect

### ISSUE THREAD

**Issue by tanker11** [t1gr0u/rain-gauge-card#16]
If I set/change the option for max_level, no any change in the displaying.

**Comment by tanker11** [comment]
Sure, sorry.
Here is my config:
type: custom:rain-gauge-card
entity: sensor.rain_24h
show_warning: false
show_error: false
is_imperial: false
max_level: 3

What I get is:
![image](https://github.com/t1gr0u/rain-gauge-card/assets/32165691/59841530-10dd-4db0-8486-fcd6772c6a15)

According to my understanding the level should be around 1/3 of the total height, right?
If I change the max_level to 2, nothing changes in the displaying, however it should be about 1/2 of the total height with the actual value of 1.1.

**Comment by t1gr0u** [comment]
@tanker11 I've set the minimum to be `40mm` so if the `max_level` is anything below this then it will not take this into account.
But if you set this anything above then it will work.

I just wanted to be defensive within the code.

**Comment by tanker11** [comment]
Okay, noted. :)
It is a pity, because in my country a typical value is much less, so it
would rarely show bigger amounts than something in the bottom of the drop
then...
I will not remarkably see the difference between 2 and 5mm.

Anyway, thanks for the clarification.

Marc Sygrove ***@***.***> ezt írta (időpont: 2023. máj. 16.,
K, 15:26):

**Comment by t1gr0u** [comment]
If I get more requests to drop the minimum (40mm) then I would consider it :)

**Comment by tanker11** [comment]
Ok, thanks for that.

Marc Sygrove ***@***.***> ezt írta (időpont: 2023. máj. 16.,
Ke 15:36):

**Comment by maccan-tech** [comment]
+1
Maby let oss be able set the minimum value.

**Comment by Gavin-A92** [comment]
I'd like to leave a +1 for this change too.....IMHO 40mm is excessive as a min level for the Gauge.

As example almost biblical rain yesterday here (Ireland) but still only hitting 27mm of rain in 24 hours.....going back over past 12 months the max daily rain here was 37mm......not sure where dev is from so maybe 40mm+ daily is usual (tho you're UK I think so unlikely)....anyway just my thoughts.....

**Comment by steve125125** [comment]
It works of i set is-imperial to true. 

But it would be nice if this works with mm as well. 

type: custom:rain-gauge-card
language: de
name: Regen
show_error: false
show_warning: false
entity: sensor.innen_innen_innen_regen_pws_rain_today
hourly_rate_entity: sensor.innen_innen_innen_regen_pws_rain
is_imperial: true
max_level: '8'

**Comment by t1gr0u** [comment]
@tanker11 this is now fixed in v1.4.0, thank you for using this card.
