### ISSUE TITLE
Rain drop should not be filled if there was no rain today

### ISSUE THREAD

**Issue by AndLindemann** [t1gr0u/rain-gauge-card#19]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:** 1.3.0

**Last working release (if known):** n/a

**Browser and Operating System:** all of them

**Description of problem:**
If there is 0.0mm of daily rain, there is still some water in the rain drop bubble.
So looking briefly on the dashboard it'd look like it had rained today when it really didn't.

Expectation: 
Rain drop should be empty (no blue fill), if there wasn't any actual rain.
Would be great if this can be adjusted. I think using 188 as the "rainlevel" instead of 180 will drop the blue box deep enough that it is not visible if there is 0 actual rainfall.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
![rain](https://github.com/t1gr0u/rain-gauge-card/assets/4157845/2e66a2c4-43f5-4fdb-8eeb-91f73fa8644e)

**Comment by Scoop2389** [comment]
+1 Would like to see this fixed because it is hard to tell the difference between no rain and little rain

**Comment by t1gr0u** [comment]
@AndLindemann this is now fixed in v1.4.0, thank you for using this card.

**Comment by t1gr0u** [comment]
@Scoop2389 this is now fixed in v1.4.0, thank you for using this card.
