### ISSUE TITLE
Inches

### ISSUE THREAD

**Issue by mattfox27** [t1gr0u/rain-gauge-card#3]
Can you make this so it can also do In/hr for US?  Really like it

**Comment by 715Steve** [comment]
Agree. My weather station uses inches.

unit_of_measurement: in

Thanks.

**Comment by t1gr0u** [comment]
@mattfox27 @715Steve We could have a boolean like `is_imperial` if set to `true` will then change all the unit of measurement to use `in` for `Total` and `in/h` for the `Rate`.

What do you think?

**Comment by 715Steve** [comment]
Manually is fine, just so long as there is a way to change it.

**Comment by mattfox27** [comment]
Either option works for me

**Comment by t1gr0u** [comment]
This is now added in v1.2.0

You can either add `is_imperial` in the YAML editor and set it to `true`
or use the UI and toggle the switch.

**Comment by 715Steve** [comment]
Updated and it works great. Thanks!
