### ISSUE TITLE
Rain level not updating

### ISSUE THREAD

**Issue by geidorei** [t1gr0u/rain-gauge-card#30]
Sensor not updating?

It's rained quite a lot today but there's no data showing. BTW I'm in Scotland, it does rain a lot!

Config:
  type: custom:rain-gauge-card
  entity: sensor.rain_daily

Am I missing something?

Many thanks.

**Comment by t1gr0u** [comment]
Hi @geidorei could please post a history/graph of `sensor.rain_daily`.

**Comment by geidorei** [comment]
Right, I am missing something..... The sensor 'sensor.rain_daily' doesnt exist in my HA entities.

What have I done wrong?

Thanking you in advance.

**Comment by t1gr0u** [comment]
@geidorei Do you have a weather station? or can you pull the information from a weather integration?

**Comment by geidorei** [comment]
Ah ha lol. Right no weather station and the weather ints all seems to be either broken, or a cost is involved. Any suggestions?

**Comment by t1gr0u** [comment]
@geidorei I had a look at the [met office](https://www.home-assistant.io/integrations/metoffice/) integration and I can't see it in there, they only have the probability of precipitation.

**Comment by geidorei** [comment]
Wonderful... lol. I'll have another look.....

**Comment by jazzyisj** [comment]
http://pirateweather.net
